wandb: Currently logged in as: jeroenov98. Use `wandb login --relogin` to force relogin
wandb: Tracking run with wandb version 0.16.2
wandb: Run data is saved locally in /home/jvrielink/Thesis/SparK/pretrain/debug/debug_01-10_15:17:51/wandb/run-20240110_151752-guvpkue8
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run debug_01-10_15:17:51
wandb:  View project at https://wandb.ai/jeroenov98/AIML-SSL
wandb:  View run at https://wandb.ai/jeroenov98/AIML-SSL/runs/guvpkue8
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=> Traceback (most recent call last):
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/Thesis/SparK/pretrain/main.py", line 329, in <module>
    main_pt()
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/Thesis/SparK/pretrain/main.py", line 66, in main_pt
    dataset_train = build_dataset_to_pretrain(args.annotations_file, args.data_path, args.input_size)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/Thesis/SparK/pretrain/utils/imagenet.py", line 126, in build_dataset_to_pretrain
    dataset_train = AIMLDataset(annotations_file, dataset_path, mod_trans_train)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/Thesis/SparK/pretrain/utils/imagenet.py", line 42, in __init__
    self.img_paths_labels = pd.read_csv(os.path.join(data_path, annotations_file))
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/anaconda3/envs/spark/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 948, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/anaconda3/envs/spark/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 611, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/anaconda3/envs/spark/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1448, in __init__
    self._engine = self._make_engine(f, self.engine)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/anaconda3/envs/spark/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1705, in _make_engine
    self.handles = get_handle(
                   ^^^^^^^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=>   File "/home/jvrielink/anaconda3/envs/spark/lib/python3.11/site-packages/pandas/io/common.py", line 863, in get_handle
    handle = open(
             ^^^^^
[01-10 12:47:55] (/python3.11/traceback.py, line1018)=> FileNotFoundError: [Errno 2] No such file or directory: '/mnt/sdb1/Data_remote/AIML_rot_corrected/annotations/imgs_paths_mini.csv'
